[package]
name = "twistykeys"
version = "0.1.0"
edition = "2021"

[dependencies]
aes = "0.8"
anyhow = "1.0"
btleplug = "0.11"
enigo = "0.6.1"
futures-util = "0.3"
thiserror = "1.0"
tokio = "1.38"

[target.'cfg(unix)'.dependencies]
nix = "0.30.1"
input-linux = "0.7.1"
